"""
TradePass Streamlit Frontend
Wraps the FastAPI backend (port 8000) with a functional UI.
All study endpoints require JWT auth; token stored in st.session_state.
"""
import os
import streamlit as st
import requests
import plotly.express as px
import plotly.graph_objects as go
import time
from datetime import datetime, date

BASE_URL = os.environ.get("TRADEPASS_API_URL", "http://localhost:8000")

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def api_headers():
    """Return Authorization header dict if token is present."""
    token = st.session_state.get("jwt_token", "")
    if token:
        return {"Authorization": f"Bearer {token}"}
    return {}


def api_get(path: str, params: dict = None):
    r = requests.get(f"{BASE_URL}{path}", headers=api_headers(), params=params, timeout=15)
    if r.status_code == 401:
        st.session_state["jwt_token"] = ""
        st.session_state["user_id"] = None
        st.error("Session expired. Please log in again.")
        st.session_state["page"] = "Login"
        return None
    if not r.ok:
        st.error(f"API error {r.status_code}: {r.text[:200]}")
        return None
    return r.json()


def api_post(path: str, payload: dict = None):
    r = requests.post(f"{BASE_URL}{path}", json=payload, headers=api_headers(), timeout=15)
    if r.status_code == 401:
        st.session_state["jwt_token"] = ""
        st.session_state["user_id"] = None
        st.error("Session expired. Please log in again.")
        st.session_state["page"] = "Login"
        return None
    if not r.ok:
        st.error(f"API error {r.status_code}: {r.text[:200]}")
        return None
    return r.json()


def api_put(path: str, payload: dict = None):
    r = requests.put(f"{BASE_URL}{path}", json=payload, headers=api_headers(), timeout=15)
    if not r.ok:
        st.error(f"API error {r.status_code}: {r.text[:200]}")
        return None
    return r.json()


def require_auth():
    if not st.session_state.get("jwt_token"):
        st.warning("Please log in to access this page.")
        st.session_state["page"] = "Login"
        st.rerun()


def fmt_pct(val):
    if val is None:
        return "N/A"
    return f"{val:.1f}%"


def session_summary(session_type, timestamp, score_pct, accuracy_pct, topics_covered, correct_count=None, total_count=None, passed=None):
    """Build a plain-text session summary for copying/sharing."""
    lines = [
        f"📊 TradePass Study Report",
        f"━━━━━━━━━━━━━━━━━━",
        f"Type: {session_type}",
        f"When: {timestamp[:10] if timestamp else 'Just now'}",
    ]
    if correct_count is not None and total_count is not None:
        lines.append(f"Score: {score_pct:.1f}% ({correct_count}/{total_count} correct)")
    else:
        lines.append(f"Score: {score_pct:.1f}%")
    lines.append(f"Accuracy: {accuracy_pct:.1f}%")
    if passed is not None:
        lines.append(f"Result: {'✅ PASSED' if passed else '❌ FAILED'}")
    if topics_covered:
        lines.append(f"Topics: {', '.join(topics_covered)}")
    lines.append("━━━━━━━━━━━━━━━━━━")
    lines.append("Generated by TradePass — tradepass.app")
    return "\n".join(lines)


def copy_button(label, text):
    """Render a Copy-to-clipboard button using JS."""
    import uuid
    btn_id = f"copybtn-{uuid.uuid4().hex[:8]}"
    st.html(f"""
<script>
function copyText_{btn_id}() {{
  navigator.clipboard.writeText({repr(text)}).then(() => {{
    document.getElementById("{btn_id}").value = "✅ Copied!";
    setTimeout(() => {{ document.getElementById("{btn_id}").value = "📋 {label}"; }}, 2000);
  }});
}}
</script>
<input type="button" id="{btn_id}" value="📋 {label}" onclick="copyText_{btn_id}()"
  style="padding:0.4rem 1rem;border-radius:0.4rem;border:1px solid #555;background:#eee;cursor:pointer;font-size:0.9rem"/>
""")


def score_color(val):
    if val is None:
        return "gray"
    if val >= 80:
        return "green"
    if val >= 60:
        return "orange"
    return "red"


def topic_difficulty_tag(exam_acc: float) -> str:
    """Return colour-coded difficulty emoji tag for a topic's exam accuracy."""
    if exam_acc is None:
        return ""
    if exam_acc < 50:
        return "🔴"
    if exam_acc <= 75:
        return "🟡"
    return "🟢"


def play_sound(sound_type: str = "success"):
    """Play a subtle Web Audio API tone once per results screen load.

    sound_type: 'success' (passing) or 'fail' (low score).
    Uses session_state guard so it never replays on rerun.
    """
    key = f"sound_played_{sound_type}_{st.session_state.get('page', 'unknown')}"
    if st.session_state.get(key, False):
        return
    st.session_state[key] = True

    if sound_type == "success":
        # Ascending tone: 440Hz → 880Hz over 200ms
        freq_start, freq_end, duration = 440, 880, 200
    else:
        # Descending minor tone: 440Hz → 330Hz over 250ms
        freq_start, freq_end, duration = 440, 330, 250

    st.html(f"""
<script>
(function () {{
  const ctx = new (window.AudioContext || window.webkitAudioContext)();
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.connect(gain);
  gain.connect(ctx.destination);
  osc.startTime = ctx.currentTime;
  osc.endTime = ctx.currentTime + {duration_ms} / 1000;
  osc.frequency.setValueAtTime({freq_start}, ctx.currentTime);
  osc.frequency.linearRampToValueAtTime({freq_end}, ctx.currentTime + {duration_ms} / 1000);
  gain.gain.setValueAtTime(0.15, ctx.currentTime);
  gain.gain.linearRampToValueAtTime(0, ctx.currentTime + {duration_ms} / 1000);
  osc.start();
  osc.onended = () => ctx.close();
}})();
</script>
""".format(freq_start=freq_start, freq_end=freq_end, duration_ms=duration))


# ─────────────────────────────────────────────────────────────────────────────
# Share / Export helpers
# ─────────────────────────────────────────────────────────────────────────────

TOPIC_NAMES = {
    1: "Knowledge of Trade Instruments", 2: "Securities Taxation",
    3: "Market Manipulation", 4: "Ethical Conduct", 5: "Corporate Actions",
    6: "Client Suitability", 7: "Market Regulation", 8: "Asset Segregation",
    9: "Best Execution", 10: "Insider Trading", 11: "ADR Operations",
}


def session_summary_study(result: dict) -> str:
    """Format a graded Study Session result as a plain-text shareable block."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    reviewed = result.get("total_reviewed", 0)
    correct = result.get("correct_count", 0)
    acc = result.get("accuracy_pct", 0)
    ef = result.get("new_easiness_factor", 0)
    return (
        f"📚 TradePass Study Session — {ts}\n"
        f"─────────────────────────────\n"
        f"Questions reviewed: {reviewed}\n"
        f"Correct answers: {correct}\n"
        f"Accuracy: {acc:.1f}%\n"
        f"New easiness factor: {ef:.2f}\n"
        f"─────────────────────────────\n"
        f"#TradePass #StudySession"
    )


def session_summary_exam(result: dict) -> str:
    """Format an Exam result as a plain-text shareable block."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    score = result.get("score_percent", 0)
    passed = "✅ PASSED" if result.get("passed") else "❌ FAILED"
    correct = result.get("passed_count", 0)
    total = result.get("total_count", 0)
    breakdown = result.get("topic_breakdown", [])
    lines = [
        f"📝 TradePass Exam — {ts}",
        f"─────────────────────────────",
        f"Result: {passed} | Score: {score:.1f}%",
        f"Correct: {correct}/{total} | Pass mark: 70%",
    ]
    if breakdown:
        lines.append("Topic breakdown:")
        for b in breakdown:
            t_name = TOPIC_NAMES.get(b.get("topic_id"), f"Topic {b.get('topic_id')}")
            pct = b.get("accuracy_pct", 0)
            c = b.get("correct", 0)
            t = b.get("total", 0)
            lines.append(f"  • {t_name}: {pct:.1f}% ({c}/{t})")
    lines.append("─────────────────────────────")
    lines.append("#TradePass #ExamMode")
    return "\n".join(lines)


def session_summary_focus(result: dict, topic_map: dict) -> str:
    """Format a Focus Mode result as a plain-text shareable block."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    score = result.get("score_percent", 0)
    correct = result.get("correct_count", 0)
    total = result.get("total_count", 0)
    topic_id = result.get("topic_id", 0)
    topic_name = topic_map.get(topic_id, f"Topic {topic_id}")
    verdict = "✅ PASSED" if result.get("passed") else "❌ Keep practicing"
    return (
        f"🎯 TradePass Focus Mode — {ts}\n"
        f"─────────────────────────────\n"
        f"Topic: {topic_name}\n"
        f"Score: {score:.1f}% ({correct}/{total})\n"
        f"Result: {verdict}\n"
        f"─────────────────────────────\n"
        f"#TradePass #FocusMode"
    )


def copy_results_button(text: str, label: str = "📋 Copy Results"):
    """Render a Streamlit button that copies `text` to the clipboard via JS."""
    import urllib.parse
    escaped = text.replace("\n", "↵").replace('"', '&quot;')
    st.html(
        f"""
        <script>
        async function copyText() {{
            try {{
                await navigator.clipboard.writeText("{text}");
            }} catch(e) {{
                /* fallback for environments without clipboard API */
            }}
        }}
        </script>
        """
    )
    # Use a form+button approach so clicks are captured cleanly
    components = f"""
    <div id="tp-copy-zone" style="margin-top:8px;">
      <button
        onclick="navigator.clipboard.writeText(`{text}`).catch(()=>{{}})"
        style="
          background:#2E7D32; color:white; border:none; border-radius:6px;
          padding:8px 18px; font-size:15px; cursor:pointer;
          display:inline-flex; align-items:center; gap:6px;
        "
      >📋 Copy Results</button>
      <span id="tp-copy-msg" style="margin-left:10px; color:#2E7D32; font-size:14px; display:none;">✅ Copied!</span>
    </div>
    <script>
      const btn = document.querySelector('button[onclick*="navigator.clipboard"]');
      if (btn) {{
        btn.addEventListener('click', () => {{
          const msg = document.getElementById('tp-copy-msg');
          if (msg) {{
            msg.style.display = 'inline';
            setTimeout(() => {{ msg.style.display = 'none'; }}, 2000);
          }}
        }});
      }}
    </script>
    """
    st.html(components)


# ─────────────────────────────────────────────────────────────────────────────
# Initialise session state
# ─────────────────────────────────────────────────────────────────────────────

for key, default in [
    ("jwt_token", ""),
    ("user_id", None),
    ("display_name", ""),
    ("email", ""),
    ("page", "Login"),
    ("registered", False),
]:
    st.set_page_config(key=key, initial_value=default)


def _init_state():
    defaults = {
        "jwt_token": "",
        "user_id": None,
        "display_name": "",
        "email": "",
        "page": "Login",
        "registered": False,
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

_init_state()


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar navigation
# ─────────────────────────────────────────────────────────────────────────────

def sidebar_nav():
    with st.sidebar:
        st.title("TradePass")
        if st.session_state.get("jwt_token"):
            profile = api_get(f"/api/study/profile/{st.session_state['user_id']}")
            if profile:
                st.success(f"✓ {profile.get('display_name', st.session_state.get('display_name',''))}")
            pages = ["Dashboard", "Study Session", "Focus Mode", "Exam Mode", "Topic Trends", "Achievements", "History", "Study Plan", "Profile"]
            icons = ["📊", "📖", "🎯", "📝", "📈", "🏆", "🕐", "📅", "👤"]
        else:
            pages = ["Login"]
            icons = ["🔑"]
        choice = st.radio("Navigate", pages, index=pages.index(st.session_state.get("page", "Dashboard"))
                          if st.session_state.get("page","Dashboard") in pages else 0,
                          format_func=lambda x: f"{icons[pages.index(x)]} {x}")
        if choice != st.session_state.get("page"):
            st.session_state["page"] = choice
            st.rerun()
        st.divider()
        if st.session_state.get("jwt_token"):
            if st.button("🔓 Log out"):
                st.session_state["jwt_token"] = ""
                st.session_state["user_id"] = None
                st.session_state["page"] = "Login"
                st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Login / Register
# ─────────────────────────────────────────────────────────────────────────────

def page_login():
    st.title("🔐 TradePass")
    # ── Demo account quick-access ───────────────────────────────────────────
    # ── Demo Options expander ──────────────────────────────────────────────
    with st.expander("🗂 Compare Demo Profiles", expanded=False):
        st.caption("Choose a profile to preview different user states:")
        col_a, col_b = st.columns(2)
        with col_a:
            st.info("✅ **Successful Learner**  | `demo@test.com` / `demo1234`  | Established learner — 9-day streak, 63% accuracy, full history.")
            if st.button("Load Successful Learner", key="demo_successful", use_container_width=True):
                st.query_params["demo_email"] = "demo@test.com"
                st.query_params["demo_pw"] = "demo1234"
                st.rerun()
        with col_b:
            st.warning("⚠️ **Struggling Beginner**  | `power@test.com` / `power1234`  | Novice learner — 33% accuracy, 11 weak topics, Focus Mode active.")
            if st.button("Load Struggling Beginner", key="demo_struggling", use_container_width=True):
                st.query_params["demo_email"] = "power@test.com"
                st.query_params["demo_pw"] = "power1234"
                st.rerun()

    # Pre-fill demo_email/pw from Demo Options (survives rerun via query_params)
    if "demo_email" in st.query_params and "demo_pw" in st.query_params:
        st.session_state["demo_email"] = st.query_params["demo_email"]
        st.session_state["demo_pw"] = st.query_params["demo_pw"]
    demo_email_preselect = st.session_state.pop("demo_email", "")
    demo_pw_preselect = st.session_state.pop("demo_pw", "")

    # ── Demo account quick-access ───────────────────────────────────────────
    st.info("**demo@test.com / demo1234** — click below to explore without registering.")
    st.success("🚀 **Demo account pre-filled** — just click to log in instantly.")
    if st.button("🚀 Try Demo Account", type="primary", use_container_width=True):
        with st.spinner("Logging in as demo…"):
            r = requests.post(
                f"{BASE_URL}/api/auth/login",
                json={"email": "demo@test.com", "password": "demo1234"},
                timeout=10,
            )
        if r.status_code == 200:
            data = r.json()
            st.session_state["jwt_token"] = data.get("access_token", "")
            st.session_state["user_id"] = data.get("user_id", "demo-user-001")
            st.session_state["email"] = "demo@test.com"
            st.session_state["display_name"] = data.get("display_name", "Demo User")
            st.session_state["page"] = "Dashboard"
            st.rerun()
        else:
            try:
                err = r.json().get("detail", r.text[:200])
            except Exception:
                err = r.text[:200]
            st.error(f"Demo login failed ({r.status_code}): {err}")
    st.divider()
    tab1, tab2 = st.tabs(["Log in", "Register"])
    with tab1:
        with st.form("login_form", clear_on_submit=True):
            email = st.text_input("Email", placeholder="you@example.com", key="login_email",
                             value=demo_email_preselect)
            password = st.text_input("Password", type="password", key="login_pw",
                             value=demo_pw_preselect)
            submitted = st.form_submit_button("Log in", use_container_width=True)
            if submitted:
                if not email or not password:
                    st.warning("Fill in both fields.")
                else:
                    with st.spinner("Signing in…"):
                        r = requests.post(
                            f"{BASE_URL}/api/auth/login",
                            json={"email": email, "password": password},
                            timeout=10,
                        )
                    if r.status_code == 200:
                        data = r.json()
                        st.session_state["jwt_token"] = data.get("access_token", "")
                        st.session_state["email"] = email
                        # fetch user_id from profile by email (no token needed for login)
                        # Login response should include user_id; if not, look it up
                        st.session_state["user_id"] = data.get("user_id", email)
                        st.session_state["display_name"] = data.get("display_name", "")
                        st.session_state["page"] = "Dashboard"
                        st.rerun()
                    else:
                        st.error(f"Login failed: {r.json().get('detail', r.text)[:200]}")
    with tab2:
        with st.form("register_form", clear_on_submit=True):
            email = st.text_input("Email", placeholder="you@example.com", key="reg_email")
            password = st.text_input("Password", type="password", key="reg_pw")
            display_name = st.text_input("Display Name", placeholder="Your name", key="reg_name")
            submitted = st.form_submit_button("Create account", use_container_width=True)
            if submitted:
                if not email or not password or not display_name:
                    st.warning("Fill in all three fields.")
                else:
                    with st.spinner("Creating account…"):
                        r = requests.post(
                            f"{BASE_URL}/api/auth/register",
                            json={"email": email, "password": password, "display_name": display_name},
                            timeout=10,
                        )
                    if r.status_code == 200:
                        data = r.json()
                        st.session_state["jwt_token"] = data.get("access_token", "")
                        st.session_state["email"] = email
                        st.session_state["user_id"] = data.get("user_id", email)
                        st.session_state["display_name"] = display_name
                        st.success("Account created! You're now logged in.")
                        st.session_state["page"] = "Dashboard"
                        st.rerun()
                    else:
                        st.error(f"Registration failed: {r.json().get('detail', r.text)[:200]}")


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Dashboard
# ─────────────────────────────────────────────────────────────────────────────

def page_dashboard():
    uid = st.session_state["user_id"]
    st.title("📊 Study Dashboard")
    with st.spinner("Loading dashboard…"):
        dash = api_get(f"/api/study/dashboard/{uid}")
        weekly = api_get(f"/api/study/weekly/{uid}")
        achievements = api_get(f"/api/study/achievements/{uid}")
        streaks = api_get(f"/api/study/streaks/{uid}")

    daily = api_get(f"/api/study/daily-progress/{uid}")

    if not all([dash, weekly, achievements, daily]):
        return

    # ── Quick Start Widget ─────────────────────────────────────────────────────
    st.subheader("⚡ Quick Start")
    qs1, qs2, qs3 = st.columns(3)
    qs_icons = {
        "Study Session": ("📚", "Review your cards and build your streak"),
        "Focus Mode": ("🎯", "Drill your weakest topics"),
        "Exam Mode": ("📝", "Test yourself across all topics"),
    }
    for col, (label, (icon, desc)) in zip([qs1, qs2, qs3], qs_icons.items()):
        with col:
            if st.button(f"{icon} **{label}**\n{desc}", use_container_width=True, key=f"qs_{label}"):
                st.session_state["page"] = label
                st.rerun()
    st.divider()

    # ── Motivational message below Quick Start ─────────────────────────────────
    streak_status = streaks.get("streak_status", "active")
    if streak_status == "active":
        st.success("🔥 Keep the fire alive! You're on a roll today.")
    elif streak_status == "at_risk":
        st.warning("⚠️ One more push needed! Get a few questions in to keep your streak alive.")
        if streaks.get("streak_freeze_tokens", 0) > 0:
            st.info("🧊 **Streak Freeze available** — a freeze token is protecting your streak. Use it to guarantee your streak survives the day!")
    else:
        st.error("❌ Start fresh today! Every journey begins with a single step.")

    # ── Streak fire animation (shown when streak > 0) ─────────────────────────
    streak_days = dash.get("streak_days", 0)
    if streak_days > 0:
        st.html(f"""
        <style>
        @keyframes flicker_{uid} {{
          0%,100% {{ opacity:1; transform:scale(1); }}
          25%      {{ opacity:0.85; transform:scale(1.1); }}
          50%      {{ opacity:1; transform:scale(0.97); }}
          75%      {{ opacity:0.9; transform:scale(1.05); }}
        }}
        .streak-flame-{uid} {{
          display:inline-block;
          animation:flicker_{uid} 1.4s ease-in-out infinite;
          font-size:1.1rem;
        }}
        </style>
        <span class="streak-flame-{uid}">🔥</span>
        """)

    col1, col2, col3, col4 = st.columns(4)
    freeze_tag = " 🧊" if (streaks.get("streak_freeze_tokens", 0) > 0 and streak_status == "at_risk") else ""
    col1.metric(f"🔥 Streak{freeze_tag}", f"{streak_days} days")
    col2.metric("📝 Questions Answered", f"{dash.get('total_questions_answered', 0)}")
    col3.metric("🎯 Accuracy", fmt_pct(dash.get('overall_accuracy_pct')))
    col4.metric("📅 Due Today", f"{dash.get('sm2_due_today', 0)}")

    # ── New streak record celebration ───────────────────────────────────────
    if streaks.get("current_streak", 0) > streaks.get("longest_streak", 0) and streaks.get("current_streak", 0) > 0:
        if "streak_record_fired" not in st.session_state:
            st.session_state["streak_record_fired"] = True
            st.balloons()
            longest = streaks.get("longest_streak", 0)
            current = streaks.get("current_streak", 0)
            st.success(f"🏆 **NEW RECORD!** You surpassed your longest streak of {longest} days! Current: {current} days")

    # ── Daily Goal Progress widget ─────────────────────────────────────────────
    if daily:
        done = daily.get("questions_answered_today", 0)
        goal = daily.get("daily_goal", 10)
        pct = min(done / goal, 1.0) if goal > 0 else 0
        st.progress(pct, text=f"📅 Today's goal: {done}/{goal} questions")

    if dash.get('total_questions_answered', 0) == 0:
        st.info("👋 **Welcome to TradePass!** You're starting fresh. "
                "Jump into a **Study Session** to answer your first questions, "
                "or explore with the **Demo Account** on the login screen.")

    # ── Streak at-risk banner ──────────────────────────────────────────────────
    if streak_days > 0 and streak_status != "active":
        if streak_status == "at_risk":
            st.error(f"⚠️ **Your {streak_days}-day streak is at risk!** Complete a quick 5-card review today to keep it alive.")
        elif streak_status == "broken":
            st.warning(f"💔 **Streak broken.** You missed {streaks.get('days_missed', 1)} day(s). Start a new streak today!")

    col1b, col2b, col3b, col4b = st.columns(4)
    col1b.metric("📚 Exam Sessions", f"{dash.get('exam_sessions_total', 0)}")
    col2b.metric("✅ Pass Rate", fmt_pct(dash.get('exam_pass_rate_pct')))
    col3b.metric("⏱ Est. Study Time", f"{dash.get('study_time_estimate_minutes', 0)} min")
    weekly_correct = weekly.get('accuracy_pct', 0)
    col4b.metric("📆 Weekly Accuracy", fmt_pct(weekly_correct))

    st.divider()
    st.subheader("This Week's Activity")
    wc1, wc2, wc3 = st.columns(3)
    wc1.metric("Questions This Week", f"{weekly.get('questions_answered_this_week', 0)}")
    wc2.metric("Sessions This Week", f"{weekly.get('sessions_completed_this_week', 0)}")
    wc3.metric("Topics Studied", f"{len(weekly.get('topics_studied', []))}")

    # Achievements earned count + link to full page
    st.divider()
    earned_ach = [a for a in achievements.get("achievements", []) if a.get("earned")]
    total_ach = len(achievements.get("achievements", []))
    col_ach_banner, col_ach_link = st.columns([3, 1])
    with col_ach_banner:
        st.subheader(f"🏆 Achievements  ({len(earned_ach)}/{total_ach} earned)")
    with col_ach_link:
        if st.button("View all →", use_container_width=True):
            st.session_state["page"] = "Achievements"
            st.rerun()
    if earned_ach:
        cols = st.columns(min(len(earned_ach), 5))
        for i, ach in enumerate(earned_ach[:5]):
            with cols[i]:
                badge_name = ach.get('badge_name', '')
                desc = ach.get('description', '')
                date_str = ach.get('earned_at', '')[:10]
                st.markdown(f"**{badge_name}**  {desc}  _Earned {date_str}_")
    else:
        st.info("Complete study sessions to earn achievements!")

    # Weakest / Strongest topics
    st.divider()
    col_left, col_right = st.columns(2)
    with col_left:
        st.subheader("⚠️ Weakest Topics")
        weak = dash.get("weakest_topics", [])
        if weak:
            for t in weak[:5]:
                tag = topic_difficulty_tag(t.get('accuracy_pct'))
                st.write(f"- {tag} **{t['name']}** — {fmt_pct(t.get('accuracy_pct'))}")
        else:
            st.info("📚 Not enough data yet — complete study sessions to see your weakest topics here.")
    with col_right:
        st.subheader("💪 Strongest Topics")
        strong = dash.get("strongest_topics", [])
        if strong:
            for t in strong[:5]:
                tag = topic_difficulty_tag(t.get('accuracy_pct'))
                st.write(f"- {tag} **{t['name']}** — {fmt_pct(t.get('accuracy_pct'))}")
        else:
            st.info("📚 Not enough data yet — keep studying to identify your strongest topics.")

    # Recent exams
    st.divider()
    st.subheader("📋 Recent Exams")
    recent = dash.get("recent_exams", [])
    if recent:
        for exam in recent:
            eid = exam.get("exam_id", "?")
            score = exam.get("score_percent", 0)
            passed = exam.get("passed", False)
            ts = exam.get("completed_at", "")[:16]
            st.write(f"Exam #{eid} | Score: **{fmt_pct(score)}** | {'✅ PASS' if passed else '❌ FAIL'} | {ts}")
    else:
        st.info("📝 No completed exams yet — try **Exam Mode** when you're ready.")


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Study Session
# ─────────────────────────────────────────────────────────────────────────────

def page_study_session():
    uid = st.session_state["user_id"]
    st.title("📖 Study Session")

    if "study_phase" not in st.session_state:
        st.session_state["study_phase"] = "setup"
    if "study_session_id" not in st.session_state:
        st.session_state["study_session_id"] = None
    if "study_items" not in st.session_state:
        st.session_state["study_items"] = []
    if "study_idx" not in st.session_state:
        st.session_state["study_idx"] = 0
    if "study_answers" not in st.session_state:
        st.session_state["study_answers"] = {}

    phase = st.session_state["study_phase"]

    # ── SETUP ────────────────────────────────────────────────────────────────
    if phase == "setup":
        st.info("Configure your study session, then start.")
        col_a, col_b = st.columns(2)
        with col_a:
            mode = st.selectbox("Focus", ["Review", "Focus Weak Zones", "Mixed"])
        with col_b:
            limit = st.slider("Cards per session", 5, 30, 10)

        session_limit = limit

        # Pre-session achievement snapshot (for new-achievement detection)
        if "pre_ach_count" not in st.session_state:
            ach_snapshot = api_get(f"/api/study/achievements/{uid}")
            st.session_state["pre_ach_count"] = sum(1 for a in ach_snapshot.get("achievements", []) if a.get("earned")) if ach_snapshot else 0

        if st.button("🚀 Start Session", use_container_width=True):
            with st.spinner("Building your session…"):
                payload = {"user_id": uid, "limit": session_limit}
                resp = api_post("/api/study/review-session", payload)
            if resp:
                st.session_state["study_session_id"] = resp.get("session_id")
                due = resp.get("due_reviews", [])
                new_q = resp.get("new_questions", [])
                weak = resp.get("weak_topic_quiz", [])
                all_items = due + new_q + weak
                if not all_items:
                    st.warning("No items available for study right now. All caught up! 🎉")
                    return
                st.session_state["study_items"] = all_items
                st.session_state["study_idx"] = 0
                st.session_state["study_answers"] = {}
                st.session_state["study_phase"] = "question"
                st.rerun()

    # ── QUESTION LOOP ────────────────────────────────────────────────────────
    elif phase == "question":
        items = st.session_state["study_items"]
        idx = st.session_state["study_idx"]
        total = len(items)

        if idx >= total:
            st.session_state["study_phase"] = "results"
            st.rerun()
            return

        item = items[idx]
        q_id = item.get("id")
        topic_id = item.get("topic_id")
        q_text = item.get("question_text", "No question text available.")
        explanation = item.get("explanation", "")
        difficulty = item.get("difficulty", "")

        st.progress(idx / total, text=f"Question {idx + 1} of {total}")

        with st.container():
            st.markdown(f"**Q{idx + 1}.** {q_text}")
            col_topic, col_diff = st.columns(2)
            with col_topic:
                topic_map = {
                    1: "Knowledge of Trade Instruments",
                    2: "Securities Taxation",
                    3: "Market Manipulation",
                    4: "Ethical Conduct",
                    5: "Corporate Actions",
                    6: "Client Suitability",
                    7: "Market Regulation",
                    8: "Asset Segregation",
                    9: "Best Execution",
                    10: "Insider Trading",
                    11: "ADR Operations",
                }
                st.caption(f"Topic: {topic_map.get(topic_id, f'Topic {topic_id}')}")
            with col_diff:
                st.caption(f"Difficulty: {difficulty}")

            # Show/hide answer toggle
            with st.expander("📖 Show Answer"):
                st.success(item.get("answer_text", "No answer provided."))
                if explanation:
                    st.info(f"💡 {explanation}")

            user_guess = st.radio(
                "Did you know it?",
                ["Knew it ✓", "Didn't know ✗"],
                key=f"q_{idx}",
                index=None,
            )

            c1, c2 = st.columns(2)
            with c1:
                next_label = "Next →" if idx < total - 1 else "Finish Session"
                if st.button(next_label, use_container_width=True):
                    st.session_state["study_answers"][q_id] = (user_guess == "Knew it ✓")
                    st.session_state["study_idx"] += 1
                    st.rerun()
            with c2:
                if st.button("↩️ End Early", use_container_width=True):
                    st.session_state["study_phase"] = "results"
                    st.rerun()

    # ── RESULTS ──────────────────────────────────────────────────────────────
    elif phase == "results":
        session_id = st.session_state.get("study_session_id")
        st.title("📊 Session Complete!")

        if session_id and st.session_state["study_answers"]:
            # Build grade payload
            grade_payload = {
                "user_id": uid,
                "session_id": session_id,
                "answers": {
                    str(q_id): {"correct": val}
                    for q_id, val in st.session_state["study_answers"].items()
                },
            }
            with st.spinner("Grading session…"):
                result = api_post(f"/api/study/review-session/{session_id}/grade", grade_payload)

            if result:
                st.success(f"Session graded! {result.get('total_reviewed', 0)} items reviewed.")
                # Check for new achievements earned during this session
                pre_count = st.session_state.get("pre_ach_count", 0)
                ach_data = api_get(f"/api/study/achievements/{uid}")
                earned_now = sum(1 for a in ach_data.get("achievements", []) if a.get("earned")) if ach_data else 0
                if earned_now > pre_count:
                    st.balloons()
                    new_badges = earned_now - pre_count
                    st.success(f"🎉 You earned {new_badges} new achievement{'s' if new_badges > 1 else ''}!")
                st.session_state["pre_ach_count"] = earned_now
                acc = result.get("accuracy_pct", 0)
                play_sound("success" if acc >= 70 else "fail")
                col1, col2, col3 = st.columns(3)
                col1.metric("Reviewed", result.get("total_reviewed", 0))
                col2.metric("Correct", result.get("correct_count", 0))
                col3.metric("Accuracy", fmt_pct(result.get("accuracy_pct")))
                new_ef = result.get("new_easiness_factor", 0)
                st.info(f"Updated average easiness factor: {new_ef:.2f}")
                # Copyable summary
                session_ts = datetime.now().isoformat()
                topics_list = [item.get("topic_name", f"Topic {item.get('topic_id', '?')}") for item in st.session_state.get("study_items", [])]
                summary_text = session_summary(
                    "Study Session", session_ts,
                    result.get("accuracy_pct", 0), result.get("accuracy_pct", 0),
                    topics_list,
                    result.get("correct_count", 0), result.get("total_reviewed", 0),
                    None
                )
                st.markdown("—")
                st.markdown("**📋 Share Results**")
                copy_button("Copy Results", summary_text)
            else:
                st.warning("Grading failed — results not saved.")
        else:
            st.info("No answers were recorded.")

        if st.button("🔄 Study Again"):
            for k in ["study_phase", "study_session_id", "study_items", "study_idx", "study_answers"]:
                st.session_state[k] = [] if k == "study_items" else {} if k in ("study_answers",) else "setup"
            st.session_state["study_phase"] = "setup"
            st.rerun()

        if st.button("📊 Go to Dashboard"):
            st.session_state["page"] = "Dashboard"
            for k in ["study_phase", "study_session_id", "study_items", "study_idx", "study_answers"]:
                st.session_state[k] = [] if k == "study_items" else {} if k in ("study_answers",) else "setup"
            st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Exam Mode
# ─────────────────────────────────────────────────────────────────────────────

def page_exam_mode():
    uid = st.session_state["user_id"]
    st.title("📝 Exam Mode")

    if "exam_phase" not in st.session_state:
        st.session_state["exam_phase"] = "setup"
    if "exam_session_id" not in st.session_state:
        st.session_state["exam_session_id"] = None
    if "exam_questions" not in st.session_state:
        st.session_state["exam_questions"] = []
    if "exam_idx" not in st.session_state:
        st.session_state["exam_idx"] = 0
    if "exam_answers" not in st.session_state:
        st.session_state["exam_answers"] = {}
    if "exam_start_time" not in st.session_state:
        st.session_state["exam_start_time"] = None
    if "exam_duration_min" not in st.session_state:
        st.session_state["exam_duration_min"] = 20

    phase = st.session_state["exam_phase"]

    # ── SETUP ────────────────────────────────────────────────────────────────
    if phase == "setup":
        st.warning("⚠️  Exam mode is timed. Submit before the timer expires.")
        num_q = st.slider("Number of questions", 5, 30, 15)
        duration = st.slider("Duration (minutes)", 5, 60, 20)
        st.session_state["exam_duration_min"] = duration

        # Build accuracy-aware topic labels for the multiselect
        priority_data = api_get(f"/api/study/priority/{uid}")
        topic_acc_map = {}
        if priority_data and priority_data.get("topics"):
            for t in priority_data["topics"]:
                topic_acc_map[t["topic_id"]] = t.get("exam_accuracy_pct")
        topic_id_to_name = {
            1: "Knowledge of Trade Instruments",
            2: "Securities Taxation",
            3: "Market Manipulation",
            4: "Ethical Conduct",
            5: "Corporate Actions",
            6: "Client Suitability",
            7: "Market Regulation",
            8: "Asset Segregation",
            9: "Best Execution",
            10: "Insider Trading",
            11: "ADR Operations",
        }
        topic_ids = list(range(1, 12))
        selected_topics = st.multiselect(
            "Topics to include (leave all to include all)",
            options=topic_ids,
            default=[],
            format_func=lambda x: f"{topic_difficulty_tag(topic_acc_map.get(x))} {topic_id_to_name.get(x, f'Topic {x}')}",
        )
        st.session_state["selected_topics"] = selected_topics

        st.info("💡 **How it works:** Select topics above, or leave all empty to include every topic.")
        # Pre-session achievement snapshot
        if "pre_ach_count" not in st.session_state:
            ach_snapshot = api_get(f"/api/study/achievements/{uid}")
            st.session_state["pre_ach_count"] = sum(1 for a in ach_snapshot.get("achievements", []) if a.get("earned")) if ach_snapshot else 0

        if st.button("🚦 Start Exam", use_container_width=True):
            with st.spinner("Setting up exam…"):
                payload = {
                    "user_id": uid,
                    "num_questions": num_q,
                    "topics": selected_topics if selected_topics else None,
                }
                resp = api_post("/api/study/exam-session", payload)
            if resp:
                st.session_state["exam_session_id"] = resp.get("exam_session_id")
                st.session_state["exam_questions"] = resp.get("questions", [])
                st.session_state["exam_answers"] = {}
                st.session_state["exam_idx"] = 0
                st.session_state["exam_start_time"] = time.time()
                st.session_state["exam_phase"] = "exam"
                st.rerun()
            else:
                st.error("Failed to start exam session.")

    # ── EXAM LOOP ────────────────────────────────────────────────────────────
    elif phase == "exam":
        questions = st.session_state["exam_questions"]
        idx = st.session_state["exam_idx"]
        total = len(questions)
        elapsed_s = time.time() - st.session_state["exam_start_time"]
        total_s = st.session_state["exam_duration_min"] * 60
        remaining_s = max(0, total_s - elapsed_s)
        remaining_min = int(remaining_s // 60)
        remaining_sec = int(remaining_s % 60)

        # Auto-submit on time
        if remaining_s <= 0:
            st.warning("⏰ Time's up! Submitting exam…")
            st.session_state["exam_phase"] = "submitting"
            st.rerun()
            return

        # Timer display
        timer_col = st.columns([3, 1])
        with timer_col[0]:
            st.markdown(
                f"### ⏱ {remaining_min:02d}:{remaining_sec:02d} remaining"
                + (" ⚠️" if remaining_s < 120 else "")
            )
        with timer_col[1]:
            st.progress(1 - elapsed_s / total_s, text=f"{remaining_min}m {remaining_sec}s left")

        st.divider()
        st.caption(f"Question {idx + 1} of {total}")
        st.progress(idx / total)

        if idx >= total:
            st.session_state["exam_phase"] = "submitting"
            st.rerun()
            return

        q = questions[idx]
        q_id = q.get("id")
        topic_id = q.get("topic_id")
        q_text = q.get("question_text", "")

        topic_map = {
            1: "Knowledge of Trade Instruments", 2: "Securities Taxation",
            3: "Market Manipulation", 4: "Ethical Conduct", 5: "Corporate Actions",
            6: "Client Suitability", 7: "Market Regulation", 8: "Asset Segregation",
            9: "Best Execution", 10: "Insider Trading", 11: "ADR Operations",
        }

        st.markdown(f"**Q{idx + 1}.** {q_text}")
        st.caption(f"Topic: {topic_map.get(topic_id, f'Topic {topic_id}')}")

        options = []
        for key in ["option_a", "option_b", "option_c", "option_d"]:
            if q.get(key):
                options.append(q[key])

        answer_key = f"exam_a_{idx}"
        user_answer = st.radio("Select your answer:", options, key=answer_key, index=None)

        c1, c2 = st.columns(2)
        with c1:
            next_label = "Next →" if idx < total - 1 else "Review →"
            if st.button(next_label, use_container_width=True):
                # Map selected option back to A/B/C/D
                choice_map = {v: k for k, v in enumerate(options)}
                selected_idx = choice_map.get(user_answer)
                letter = ["A", "B", "C", "D"][selected_idx] if selected_idx is not None else None
                st.session_state["exam_answers"][q_id] = letter
                st.session_state["exam_idx"] += 1
                st.rerun()
        with c2:
            if st.button("Submit Exam Now", use_container_width=True):
                choice_map = {v: k for k, v in enumerate(options)}
                selected_idx = choice_map.get(user_answer)
                letter = ["A", "B", "C", "D"][selected_idx] if selected_idx is not None else None
                st.session_state["exam_answers"][q_id] = letter
                st.session_state["exam_phase"] = "submitting"
                st.rerun()

    # ── SUBMITTING ───────────────────────────────────────────────────────────
    elif phase == "submitting":
        exam_id = st.session_state["exam_session_id"]
        st.title("📤 Submitting Exam…")
        st.spinner("Grading your answers…")

        payload = {
            "user_id": uid,
            "exam_session_id": exam_id,
            "answers": [
                {"question_id": int(qid), "selected_option": ans}
                for qid, ans in st.session_state["exam_answers"].items()
                if ans is not None
            ],
        }
        result = api_post(f"/api/study/exam-session/{exam_id}/submit", payload)
        if result:
            st.session_state["exam_result"] = result
            st.session_state["exam_phase"] = "results"
            st.rerun()
        else:
            st.error("Failed to submit exam. Please try again.")
            st.session_state["exam_phase"] = "setup"

    # ── RESULTS ──────────────────────────────────────────────────────────────
    elif phase == "results":
        result = st.session_state.get("exam_result", {})
        st.title("📊 Exam Results")
        # Check for new achievements
        pre_count = st.session_state.get("pre_ach_count", 0)
        ach_data = api_get(f"/api/study/achievements/{uid}")
        earned_now = sum(1 for a in ach_data.get("achievements", []) if a.get("earned")) if ach_data else 0
        new_earned = earned_now - pre_count
        if new_earned > 0:
            st.balloons()
            st.success(f"🎉 You earned {new_earned} new achievement{'s' if new_earned > 1 else ''}!")
        st.session_state["pre_ach_count"] = earned_now
        score = result.get("score_percent", 0)
        passed = result.get("passed", False)
        play_sound("success" if passed else "fail")
        passed_count = result.get("passed_count", 0)
        total_count = result.get("total_count", 0)
        st.markdown(f"## {'✅ PASSED' if passed else '❌ FAILED'} — **{fmt_pct(score)}**")

        col1, col2, col3 = st.columns(3)
        col1.metric("Score", fmt_pct(score))
        col2.metric("Correct", f"{passed_count}/{total_count}")
        col3.metric("Pass Mark", f"70%")

        breakdown = result.get("topic_breakdown", [])
        if breakdown:
            st.divider()
            st.subheader("📈 Topic Breakdown")
            topics_covered = []
            for b in breakdown:
                t_name = {
                    1: "Knowledge of Trade Instruments", 2: "Securities Taxation",
                    3: "Market Manipulation", 4: "Ethical Conduct", 5: "Corporate Actions",
                    6: "Client Suitability", 7: "Market Regulation", 8: "Asset Segregation",
                    9: "Best Execution", 10: "Insider Trading", 11: "ADR Operations",
                }.get(b.get("topic_id"), f"Topic {b.get('topic_id')}")
                pct = b.get("accuracy_pct", 0)
                topics_covered.append(t_name)
                st.write(f"- **{t_name}**: {fmt_pct(pct)} ({b.get('correct', 0)}/{b.get('total', 0)})")

        # Shareable summary
        session_ts = datetime.now().isoformat()
        summary_text = session_summary(
            "Exam Session", session_ts,
            score, result.get("accuracy_pct", score),
            topics_covered or ["Various Topics"],
            passed_count, total_count, passed
        )
        st.markdown("—")
        st.markdown("**📋 Share Results**")
        copy_button("Copy Exam Results", summary_text)

        st.divider()
        if st.button("📝 Take Another Exam"):
            for k in ["exam_phase", "exam_session_id", "exam_questions", "exam_idx", "exam_answers", "exam_result"]:
                st.session_state[k] = [] if k == "exam_questions" else {} if k == "exam_answers" else None if k in ("exam_session_id", "exam_result") else "setup"
            st.rerun()

        if st.button("📊 Dashboard"):
            st.session_state["page"] = "Dashboard"
            for k in ["exam_phase", "exam_session_id", "exam_questions", "exam_idx", "exam_answers", "exam_result"]:
                st.session_state[k] = [] if k == "exam_questions" else {} if k == "exam_answers" else None if k in ("exam_session_id", "exam_result") else "setup"
            st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Focus Mode
# ─────────────────────────────────────────────────────────────────────────────

def page_focus_mode():
    uid = st.session_state["user_id"]
    st.title("🎯 Focus Mode")

    if "focus_phase" not in st.session_state:
        st.session_state["focus_phase"] = "setup"
    if "focus_session_id" not in st.session_state:
        st.session_state["focus_session_id"] = None
    if "focus_questions" not in st.session_state:
        st.session_state["focus_questions"] = []
    if "focus_idx" not in st.session_state:
        st.session_state["focus_idx"] = 0
    if "focus_answers" not in st.session_state:
        st.session_state["focus_answers"] = {}

    phase = st.session_state["focus_phase"]

    topic_map = {
        1: "Knowledge of Trade Instruments",
        2: "Securities Taxation",
        3: "Market Manipulation",
        4: "Ethical Conduct",
        5: "Corporate Actions",
        6: "Client Suitability",
        7: "Market Regulation",
        8: "Asset Segregation",
        9: "Best Execution",
        10: "Insider Trading",
        11: "ADR Operations",
    }

    # ── SETUP ────────────────────────────────────────────────────────────────
    if phase == "setup":
        st.info("🎯 Focus Mode — drill a single weak topic with short, timed rounds.")


        # Fetch priority to populate topic options
        priority_data = api_get(f"/api/study/priority/{uid}")
        topic_options = []
        if priority_data and priority_data.get("topics"):
            for t in priority_data["topics"]:
                tid = t.get("topic_id")
                action = t.get("recommended_action", "study")
                score = t.get("priority_score", 0)
                exam_acc = t.get("exam_accuracy_pct")
                diff_tag = topic_difficulty_tag(exam_acc)
                acc_str = fmt_pct(exam_acc) if exam_acc is not None else "N/A"
                label = f"{diff_tag} {topic_map.get(tid, f'Topic {tid}')} [{action.upper()} | acc {acc_str}]"
                topic_options.append({"id": tid, "label": label, "exam_acc": exam_acc})
        else:
            # Fallback: all topics
            topic_options = [{"id": tid, "label": topic_map[tid]} for tid in range(1, 12)]


        topic_labels = [t["label"] for t in topic_options]
        selected_label = st.selectbox("Choose a topic to focus on:", topic_labels)
        selected_topic_id = topic_options[topic_labels.index(selected_label)]["id"]

        num_q = st.slider("Questions per round", 5, 10, 5)

        # Pre-session achievement snapshot
        if "pre_ach_count" not in st.session_state:
            ach_snapshot = api_get(f"/api/study/achievements/{uid}")
            st.session_state["pre_ach_count"] = sum(1 for a in ach_snapshot.get("achievements", []) if a.get("earned")) if ach_snapshot else 0

        # Streak at-risk recovery prompt
        focus_streaks = api_get(f"/api/study/streaks/{uid}")
        if focus_streaks and focus_streaks.get("streak_status") == "at_risk":
            streak_days = focus_streaks.get("current_streak", 0)
            st.warning(f"🔥 You've got a {streak_days}-day streak to protect! Let's keep it alive.")

        if st.button("🚀 Start Focus Session", use_container_width=True):
            with st.spinner("Building focus session…"):
                payload = {"user_id": uid, "topic_id": selected_topic_id, "num_questions": num_q}
                resp = api_post("/api/study/focus-session", payload)
            if resp:
                st.session_state["focus_session_id"] = resp.get("focus_session_id")
                st.session_state["focus_questions"] = resp.get("questions", [])
                st.session_state["focus_topic_id"] = selected_topic_id
                st.session_state["focus_answers"] = {}
                st.session_state["focus_idx"] = 0
                st.session_state["focus_phase"] = "focus"
                st.rerun()
            else:
                st.error("❌ Could not start focus session.")
            st.info("💡 **Tip:** Focus Mode needs weak-topic history. "
                    "Complete some **Study Sessions** first to build data, "
                    "then come back to drill your weak spots.")
            st.caption("Expected for brand-new users: start with Study Session → then try Focus Mode.")

    # ── FOCUS LOOP ────────────────────────────────────────────────────────────
    elif phase == "focus":
        questions = st.session_state["focus_questions"]
        idx = st.session_state["focus_idx"]
        total = len(questions)

        if idx >= total:
            st.session_state["focus_phase"] = "submitting"
            st.rerun()
            return

        st.progress(idx / total, text=f"Question {idx + 1} of {total}")
        st.caption(f"Topic: {topic_map.get(st.session_state.get('focus_topic_id', 0), '—')}")

        q = questions[idx]
        q_id = q.get("id")
        topic_id = q.get("topic_id")
        q_text = q.get("question_text", "")

        explanation = q.get("explanation", "")

        st.markdown(f"**Q{idx + 1}.** {q_text}")
        st.caption(f"Topic: {topic_map.get(topic_id, f'Topic {topic_id}')}")

        options = []
        for key in ["option_a", "option_b", "option_c", "option_d"]:
            if q.get(key):
                options.append(q[key])


        answer_key = f"focus_a_{idx}"
        user_answer = st.radio("Select your answer:", options, key=answer_key, index=None)

        # Show explanation toggle
        with st.expander("💡 Show Explanation"):
            st.info(explanation if explanation else "No explanation available.")

        c1, c2 = st.columns(2)
        with c1:
            next_label = "Next →" if idx < total - 1 else "Submit Round →"
            if st.button(next_label, use_container_width=True):
                choice_map = {v: k for k, v in enumerate(options)}
                selected_idx = choice_map.get(user_answer)
                letter = ["A", "B", "C", "D"][selected_idx] if selected_idx is not None else None
                st.session_state["focus_answers"][q_id] = letter
                st.session_state["focus_idx"] += 1
                st.rerun()
        with c2:
            if st.button("Submit Round Now", use_container_width=True):
                choice_map = {v: k for k, v in enumerate(options)}
                selected_idx = choice_map.get(user_answer)
                letter = ["A", "B", "C", "D"][selected_idx] if selected_idx is not None else None
                st.session_state["focus_answers"][q_id] = letter
                st.session_state["focus_phase"] = "submitting"
                st.rerun()

    # ── SUBMITTING ────────────────────────────────────────────────────────────
    elif phase == "submitting":
        focus_id = st.session_state["focus_session_id"]
        st.title("📤 Submitting Round…")
        st.spinner("Grading your answers…")

        payload = {
            "user_id": uid,
            "answers": [
                {"question_id": int(qid), "selected_option": ans}
                for qid, ans in st.session_state["focus_answers"].items()
                if ans is not None
            ],
        }
        result = api_post(f"/api/study/focus-session/{focus_id}/submit", payload)
        if result:
            st.session_state["focus_result"] = result
            st.session_state["focus_phase"] = "results"
            st.rerun()
        else:
            st.error("Failed to submit. Please try again.")
            st.session_state["focus_phase"] = "setup"

    # ── RESULTS ──────────────────────────────────────────────────────────────
    elif phase == "results":
        result = st.session_state.get("focus_result", {})
        st.title("🎯 Focus Round Results")

        # Check for new achievements
        pre_count = st.session_state.get("pre_ach_count", 0)
        ach_data = api_get(f"/api/study/achievements/{uid}")
        earned_now = sum(1 for a in ach_data.get("achievements", []) if a.get("earned")) if ach_data else 0
        new_earned = earned_now - pre_count
        if new_earned > 0:
            st.balloons()
            st.success(f"🎉 You earned {new_earned} new achievement{'s' if new_earned > 1 else ''}!")
        st.session_state["pre_ach_count"] = earned_now
        score = result.get("score_percent", 0)
        correct = result.get("correct_count", 0)
        total = result.get("total_count", 0)
        topic_id = result.get("topic_id", st.session_state.get("focus_topic_id", 0))
        passed = result.get("passed", False)
        play_sound("success" if passed else "fail")

        col1, col2, col3 = st.columns(3)
        col1.metric("Score", fmt_pct(score))
        col2.metric("Correct", f"{correct}/{total}")
        col3.metric("Topic", topic_map.get(topic_id, f"Topic {topic_id}"))

        st.markdown(f"**{'✅ PASSED' if passed else '❌ Keep practicing'}** — Topic accuracy after this round")

        # Shareable summary
        session_ts = datetime.now().isoformat()
        topic_name = topic_map.get(topic_id, f"Topic {topic_id}")
        summary_text = session_summary(
            f"Focus Mode — {topic_name}", session_ts,
            score, result.get("accuracy_pct", score),
            [topic_name],
            correct, total, passed
        )
        st.markdown("——")
        st.markdown("**📋 Share Results**")
        copy_button("Copy Focus Results", summary_text)

        st.divider()
        if st.button("🔄 Another Round"):
            for k in ["focus_phase", "focus_session_id", "focus_questions", "focus_idx", "focus_answers", "focus_result"]:
                st.session_state[k] = [] if k == "focus_questions" else {} if k == "focus_answers" else None if k in ("focus_session_id", "focus_result") else "setup"
            st.rerun()

        if st.button("📊 Dashboard"):
            st.session_state["page"] = "Dashboard"
            for k in ["focus_phase", "focus_session_id", "focus_questions", "focus_idx", "focus_answers", "focus_result"]:
                st.session_state[k] = [] if k == "focus_questions" else {} if k == "focus_answers" else None if k in ("focus_session_id", "focus_result") else "setup"
            st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Topic Trends
# ─────────────────────────────────────────────────────────────────────────────

def page_topic_trends():
    uid = st.session_state["user_id"]
    st.title("📈 Topic Trends")

    with st.spinner("Loading topic data…"):
        trends = api_get(f"/api/study/topics/{uid}/trends")

    if not trends:
        st.warning("No topic data available yet. Complete some study sessions first.")
        return

    topics = trends.get("topics", [])
    if not topics:
        st.info("📊 Not enough data for topic trends yet. Complete a few **Study Sessions** and **Exams** to populate this chart.")
        return

    # Bar chart — current accuracy
    fig1 = px.bar(
        x=[t["name"] for t in topics],
        y=[t.get("current_accuracy_pct", 0) or 0 for t in topics],
        color=[score_color(t.get("current_accuracy_pct")) for t in topics],
        color_discrete_map="identity",
        labels={"x": "Topic", "y": "Accuracy %"},
        title="Current Accuracy by Topic",
    )
    fig1.update_layout(showlegend=False, xaxis_tickangle=-30)
    st.plotly_chart(fig1, use_container_width=True)

    # Trend indicators
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("📊 Accuracy Details")
        for t in topics:
            cur = t.get("current_accuracy_pct")
            best = t.get("best_accuracy_pct")
            attempts = t.get("attempts_count", 0)
            trend = t.get("trend", "stable")
            trend_icon = {"improving": "↗️", "declining": "↘️", "stable": "→"}.get(trend, "—")
            st.write(
                f"**{t['name']}** {trend_icon}  "
                f"Current: {fmt_pct(cur)} | Best: {fmt_pct(best)} | "
                f"Attempts: {attempts} | Trend: {trend.capitalize()}"
            )

    with col2:
        # Best accuracy bar
        fig2 = px.bar(
            x=[t["name"] for t in topics],
            y=[t.get("best_accuracy_pct", 0) or 0 for t in topics],
            color_discrete_sequence=["#4C78A8"],
            labels={"x": "Topic", "y": "Best Accuracy %"},
            title="Best Accuracy by Topic",
        )
        fig2.update_layout(showlegend=False, xaxis_tickangle=-30)
        st.plotly_chart(fig2, use_container_width=True)

    # Priority scores
    st.divider()
    st.subheader("🎯 Topic Priority (Study Urgency)")
    priority = api_get(f"/api/study/priority/{uid}")
    if priority:
        priority_list = priority.get("topics", [])
        if priority_list:
            fig3 = px.bar(
                x=[t["name"] for t in priority_list[:8]],
                y=[t.get("priority_score", 0) for t in priority_list[:8]],
                color=[t.get("recommended_action", "study") for t in priority_list[:8]],
                color_discrete_map={
                    "exam": "#FF6B6B",
                    "review": "#FFE066",
                    "mastered": "#51CF66",
                    "study": "#339AF0",
                },
                labels={"x": "Topic", "y": "Priority Score", "color": "Action"},
                title="Study Priority (higher = more urgent)",
            )
            fig3.update_layout(xaxis_tickangle=-30)
            st.plotly_chart(fig3, use_container_width=True)

            # Action legend
            st.markdown("""
            **Action guide**: 🔴 `exam` = never attempted | 🟡 `review` = cards due
            🟢 `mastered` = >80% acc + strong EF | 🔵 `study` = general study
            """)


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Profile
# ─────────────────────────────────────────────────────────────────────────────

def page_profile():
    uid = st.session_state["user_id"]
    st.title("👤 My Profile")

    with st.spinner("Loading profile…"):
        profile = api_get(f"/api/study/profile/{uid}")
        streaks = api_get(f"/api/study/streaks/{uid}")
        daily = api_get(f"/api/study/daily-progress/{uid}")

    if not profile:
        return

    col1, col2 = st.columns(2)
    with col1:
        st.markdown(f"### {profile.get('display_name', '—')}")
        st.caption(f"📧 {profile.get('email', '—')}")
        st.caption(f"📅 Member since: {profile.get('member_since', '—')[:10]}")
    with col2:
        days = profile.get("total_study_days", 0)
        premium = profile.get("is_premium", False)
        st.metric("Total Study Days", days)
        st.write("🏅 Premium" if premium else " Free tier")

    st.divider()
    st.subheader("🔥 Streak")
    if streaks:
        col_a, col_b, col_c = st.columns(3)
        col_a.metric("Current Streak", f"{streaks.get('current_streak', 0)} days")
        col_b.metric("Longest Streak", f"{streaks.get('longest_streak', 0)} days")
        daily_goal = streaks.get("questions_per_day", 10)
        col_c.metric("Daily Goal", f"{daily_goal} questions")

        # Streak Status card
        streak_status = streaks.get("streak_status", "active")
        if streak_status == "active":
            status_label = "✅ Active"
            status_color = "green"
        elif streak_status == "at_risk":
            status_label = "⚠️ At Risk"
            status_color = "yellow"
        else:
            status_label = "❌ Broken"
            status_color = "red"

        last_date = streaks.get("last_study_date")
        streak_col1, streak_col2, streak_col3 = st.columns(3)
        streak_col1.markdown(f"**Status:** {status_label}")
        streak_col2.markdown(f"**Last Activity:** {last_date[:10] if last_date else 'Never'}")
        if streak_status != "broken":
            streak_col3.markdown("🔥 Streak is alive!")
        else:
            days_missed = streaks.get("days_missed", 0)
            streak_col3.markdown(f"❌ Missed {days_missed} day(s)")

        # Streak Freeze Tokens section
        freeze_tokens = streaks.get("streak_freeze_tokens", 0)
        st.divider()
        st.subheader("🧊 Streak Freeze Tokens")
        if freeze_tokens > 0:
            st.success(f"**{freeze_tokens} token(s) available** — protects your streak if you miss a day.")
            st.caption("Earned by maintaining your streak. Used automatically when your streak is at risk and you miss a day.")
            if streak_status == "at_risk":
                if st.button("🧊 Activate Streak Freeze Now", key="activate_freeze"):
                    resp = requests.post(
                        f"{API_URL}/api/study/streaks/{user_id}/use-freeze",
                        headers={"Authorization": f"Bearer {st.session_state['token']}"}
                    )
                    if resp.status_code == 200:
                        st.success("✅ Streak freeze activated! Your streak is protected.")
                        st.rerun()
                    else:
                        st.error(f"Failed: {resp.json().get('detail', 'Unknown error')}")
        else:
            st.info("**No tokens remaining.** Keep studying to earn more streak freeze tokens!")
            st.caption("Tokens are earned when you maintain a 7+ day streak. One freeze is consumed each time a day is missed.")

    # ── Daily Goal editor ─────────────────────────────────────────────────────
    st.divider()
    st.subheader("🎯 Daily Goal")
    current_goal = streaks.get("questions_per_day", 10) if streaks else 10
    st.caption(f"Current target: **{current_goal} questions/day**")
    goal_slider = st.slider(
        "Set your daily question target",
        min_value=1,
        max_value=100,
        value=current_goal,
        step=5,
        help="How many questions you aim to answer each day to maintain your streak."
    )
    if goal_slider != current_goal:
        if st.button("💾 Save Goal", use_container_width=True):
            r = api_put(f"/api/study/streaks/{uid}/daily-goal", payload={"goal": goal_slider})
            if r and r.get("updated"):
                st.success(f"Daily goal updated to {goal_slider} questions/day!")
                st.rerun()
            else:
                st.error("Failed to update goal. Please try again.")

    st.divider()
    st.subheader("📅 Today's Progress")
    if daily:
        done = daily.get("questions_answered_today", 0)
        goal = streaks.get("daily_goal", 10) if streaks else 10
        pct = min(done / goal, 1.0) if goal > 0 else 0
        st.progress(pct, text=f"{done}/{goal} questions today")
        st.caption(f"Accuracy today: {fmt_pct(daily.get('accuracy_today'))}")

    st.divider()
    st.subheader("⚠️ Danger Zone")
    st.warning("**Reset My Progress** — clears all study history and restarts as a fresh user. This cannot be undone.")
    if st.button("🔄 Reset My Progress", type="secondary", use_container_width=True):
        with st.spinner("Resetting…"):
            r = api_post(f"/api/study/reset-progress/{uid}", payload={})
        if r and r.get("reset"):
            st.success("Progress reset! Refreshing dashboard…")
            st.session_state["page"] = "Dashboard"
            st.rerun()
        else:
            st.error("Reset failed. Please try again.")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
# PAGE: Achievements
# ─────────────────────────────────────────────────────────────────────────────

ICON_MAP = {
    "first_session":       "🎖",
    "streak_3":            "🔥",
    "streak_7":            "🔥",
    "streak_14":           "⚡",
    "streak_30":           "👑",
    "volume_50":           "📚",
    "volume_100":          "📗",
    "volume_500":          "📕",
    "accuracy_80":         "🎯",
    "accuracy_90":         "💎",
    "first_exam_passed":   "✅",
    "exams_5_passed":       "🏅",
    "exams_10_passed":     "🏆",
    "perfect_exam":        "💯",
    "focus_drill":         "🎯",
    "focus_10":            "🔟",
    "all_topics_attempted":"🌐",
}

CATEGORY_ORDER = [
    ("Streak Milestones",  ["streak_3", "streak_7", "streak_14", "streak_30"]),
    ("Volume Milestones",   ["volume_50", "volume_100", "volume_500"]),
    ("Accuracy Milestones", ["accuracy_80", "accuracy_90"]),
    ("Exam Milestones",     ["first_exam_passed", "exams_5_passed", "exams_10_passed", "perfect_exam"]),
    ("Focus Milestones",    ["focus_drill", "focus_10"]),
    ("Coverage Milestones", ["all_topics_attempted", "first_session"]),
]

def page_achievements():
    uid = st.session_state["user_id"]
    st.title("🏆 Achievements")

    with st.spinner("Loading achievements…"):
        data = api_get(f"/api/study/achievements/{uid}")

    if data is None:
        return

    all_ach = data.get("achievements", [])
    earned_count = sum(1 for a in all_ach if a.get("earned"))
    total_count = len(all_ach)

    # Summary banner
    st.markdown(f"### You've earned **{earned_count}** out of **{total_count}** badges")
    if earned_count == total_count and total_count > 0:
        st.balloons()

    # Build lookup
    ach_by_key = {a["badge_key"]: a for a in all_ach}

    for category_name, keys in CATEGORY_ORDER:
        category_achs = [ach_by_key[k] for k in keys if k in ach_by_key]
        if not category_achs:
            continue
        earned_in_cat = sum(1 for a in category_achs if a.get("earned"))
        with st.expander(f"### {category_name}  — {earned_in_cat}/{len(category_achs)}", expanded=True):
            cols = st.columns(len(category_achs))
            for i, ach in enumerate(category_achs):
                with cols[i]:
                    icon = ICON_MAP.get(ach["badge_key"], "🏅")
                    if ach.get("earned"):
                        earned_at = ach.get("earned_at", "")
                        date_str = earned_at[:10] if earned_at else ""
                        st.markdown(
                            f"<div style='background:#1a3a1a;border-radius:8px;padding:12px;margin:4px 0;text-align:center'>"
                            f"<div style='font-size:2em'>{icon}</div>"
                            f"<div style='font-weight:bold;margin-top:4px'>{ach.get('badge_name','')}</div>"
                            f"<div style='font-size:0.85em;color:#aaa;margin-top:2px'>{ach.get('description','')}</div>"
                            f"<div style='font-size:0.8em;color:#6c6;margin-top:6px'>Earned {date_str}</div>"
                            f"</div>",
                            unsafe_allow_html=True,
                        )
                    else:
                        st.markdown(
                            f"<div style='background:#2a2a2a;border-radius:8px;padding:12px;margin:4px 0;text-align:center;opacity:0.6'>"
                            f"<div style='font-size:2em'>🔒</div>"
                            f"<div style='font-weight:bold;margin-top:4px'>{ach.get('badge_name','')}</div>"
                            f"<div style='font-size:0.85em;color:#888;margin-top:2px'>{ach.get('description','')}</div>"
                            f"</div>",
                            unsafe_allow_html=True,
                        )



# ─────────────────────────────────────────────────────────────────────────────
# PAGE: History
# ─────────────────────────────────────────────────────────────────────────────

def _score_color(pct):
    if pct is None:
        return "#888"
    if pct >= 80:
        return "#51CF66"
    if pct >= 60:
        return "#FFE066"
    return "#FF6B6B"


def _fmt_pct(val):
    if val is None:
        return "—"
    return f"{val:.0f}%"


def _type_badge(t):
    return {"exam": "📝 Exam", "focus": "🎯 Focus", "review": "📖 Review"}.get(t, t)


def _navigate_to(action, topic_name=None):
    """Navigate to the appropriate page based on recommended action."""
    if action == "focus":
        st.session_state["page"] = "Focus Mode"
    elif action == "exam":
        st.session_state["page"] = "Exam Mode"
    elif action == "review":
        st.session_state["page"] = "Study Session"
    else:
        st.session_state["page"] = "Study Session"
    st.rerun()


def page_history():
    uid = st.session_state["user_id"]
    st.title("🕐 Study History")

    # Limit selector
    col_limit, col_refresh = st.columns([1, 1])
    with col_limit:
        limit = st.selectbox("Show last", [10, 25, 50], index=0,
                             format_func=lambda x: str(x))
    with col_refresh:
        st.markdown("&nbsp;")  # spacing
        if st.button("Refresh"):
            st.rerun()

    # Fetch data
    with st.spinner("Loading history…"):
        history_data = api_get(f"/api/study/history/{uid}", {"limit": limit})
        recs_data = api_get(f"/api/study/recommendations/{uid}")

    sessions = history_data.get("sessions", []) if history_data else []
    recommendations = (recs_data.get("recommendations", []) if recs_data else [])[:3]

    # Filter tabs
    tab_all, tab_exam, tab_focus, tab_review = st.tabs(["All", "Exam", "Focus", "Review"])

    def render_session_card(s, idx):
        score = s.get("score_pct")
        correct = s.get("correct_count", 0)
        total = s.get("total_count", 0)
        duration = s.get("duration_minutes")
        sess_type = s.get("type", "")
        date_str = (s.get("date") or "")[:16]
        badge = _type_badge(sess_type)
        score_color_val = _score_color(score)

        with st.container():
            cols = st.columns([3, 1, 1, 1])
            with cols[0]:
                st.markdown(f"**{badge}**  `{date_str}`")
            with cols[1]:
                pct_display = _fmt_pct(score)
                st.markdown(
                    f"<span style='color:{score_color_val};font-weight:bold'>{pct_display}</span>"
                    f" <span style='color:#888;font-size:0.85em'>({correct}/{total})</span>",
                    unsafe_allow_html=True,
                )
            with cols[2]:
                if duration is not None:
                    st.markdown(f"⏱ `{duration:.1f}m`")
                else:
                    st.markdown("`—`")
            with cols[3]:
                passfail = "Pass" if (score is not None and score >= 70) else ("Fail" if score is not None else "")
                fc = "#51CF66" if passfail == "Pass" else ("#ff6b6b" if passfail == "Fail" else "#888")
                icon = "✅" if passfail == "Pass" else ("❌" if passfail == "Fail" else "")
                st.markdown(f"<span style='color:{fc}'>{icon} {passfail}</span>", unsafe_allow_html=True)

            # Score bar
            if score is not None:
                bar_html = (
                    f"<div style='background:#2a2a2a;border-radius:4px;height:6px;margin:4px 0 8px 0'>">
                    f"<div style='background:{score_color_val};width:{max(0,min(100,score))}%;border-radius:4px;height:6px'></div></div>"
                )
                st.markdown(bar_html, unsafe_allow_html=True)
            st.divider()

    with tab_all:
        if not sessions:
            st.info("No sessions recorded yet. Complete a Study Session, Exam, or Focus Mode to populate your history.")
        else:
            for i, s in enumerate(sessions):
                render_session_card(s, i)

    with tab_exam:
        exam_sessions = [s for s in sessions if s.get("type") == "exam"]
        if not exam_sessions:
            st.info("No completed exams yet. Try Exam Mode when you're ready!")
        else:
            for i, s in enumerate(exam_sessions):
                render_session_card(s, i)

    with tab_focus:
        focus_sessions = [s for s in sessions if s.get("type") == "focus"]
        if not focus_sessions:
            st.info("No focus sessions yet. Try Focus Mode to drill your weakest topics!")
        else:
            for i, s in enumerate(focus_sessions):
                render_session_card(s, i)

    with tab_review:
        review_sessions = [s for s in sessions if s.get("type") == "review"]
        if not review_sessions:
            st.info("No review sessions yet. Complete a Study Session to generate SM-2 flashcards.")
        else:
            for i, s in enumerate(review_sessions):
                render_session_card(s, i)

    # Recommendations section
    st.divider()
    st.subheader("💡 Personalized Recommendations")

    if not recommendations:
        st.info("Complete more sessions to unlock personalized recommendations.")
    else:
        for rec in recommendations:
            priority = rec.get("priority", "medium")
            topic = rec.get("topic_name", "")
            reason = rec.get("reason", "")
            action = rec.get("recommended_action", "study")

            priority_icon = {"high": "🔴 HIGH", "medium": "🟡 MEDIUM", "low": "🟢 LOW"}.get(priority, "")

            st.info(f"**{priority_icon} — {topic}**\n\n{reason}")
            btn_label = {
                "focus": "🎯 Start Focus Session",
                "exam": "📝 Take Exam",
                "review": "📖 Start Review",
                "any": "📖 Study Now",
            }.get(action, "📖 Start Now")
            if st.button(btn_label + " →", key=f"rec_{topic}_{action}"):
                _navigate_to(action, topic)
            st.divider()


def page_study_plan():
    uid = st.session_state["user_id"]
    st.title("📅 Study Plan")

    with st.spinner("Loading your study plan…"):
        calendar_data = api_get(f"/api/study/calendar/{uid}")
        breakdown_data = api_get(f"/api/study/topics/{uid}/due-breakdown")

    if not calendar_data or not breakdown_data:
        st.error("Could not load study plan data.")
        return

    total_due = calendar_data.get("total_due_today", 0)
    past_weeks = calendar_data.get("past_weeks", [])
    upcoming = calendar_data.get("upcoming", [])
    topic_breakdown = breakdown_data.get("topics", []) if breakdown_data else []

    # ── Summary stats ─────────────────────────────────────────────────────
    streak_today = sum(1 for p in past_weeks[-7:] if p.get("had_activity"))
    col_s1, col_s2, col_s3 = st.columns(3)
    with col_s1:
        st.metric("🔥 Due Today", total_due)
    with col_s2:
        st.metric("📅 Active Days (7d)", streak_today)
    with col_s3:
        total_upcoming = sum(d.get("due_count", 0) for d in upcoming)
        st.metric("📬 Due Next 14d", total_upcoming)

    st.divider()

    # ── Activity Calendar: 4-week heatmap ──────────────────────────────────
    st.subheader("📆 Activity Calendar — Last 4 Weeks")

    # Group past_weeks into weeks (7 days each)
    # Display as 4 rows of 7 columns (Mon–Sun)
    DAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

    # Pad start so first day aligns correctly (week starts Monday)
    # We want a 4x7 grid flattened from 28 days
    grid_days = past_weeks  # already chronological oldest→newest

    # Build grid as list of weeks
    weeks = [grid_days[i*7:(i+1)*7] for i in range(4)]

    # Header row
    header_cols = st.columns([1] + [1]*7)
    header_cols[0].write("")
    for i, day_label in enumerate(DAY_LABELS):
        header_cols[i+1].write(f"<sub>{day_label}</sub>", unsafe_allow_html=True)

    # Week rows
    streak_count = 0
    for week in weeks:
        cols = st.columns([1] + [1]*7)
        # Label week number
        cols[0].write(f"<sub>Wk</sub>", unsafe_allow_html=True)
        for i, day in enumerate(week):
            active = day.get("had_activity", False)
            questions = day.get("questions_answered", 0)
            date_label = day.get("date", "")[-5:]  # MM-DD
            # Color: green if active, grey if not
            bg = "#51cf66" if active else "#404040"
            text_color = "#ffffff" if active else "#888888"
            # Tooltip on hover via title
            cell_html = (
                f"<div title='{date_label}: {questions} Qs' "
                f"style='background:{bg};border-radius:4px;padding:6px 2px;text-align:center;color:{text_color};font-size:0.8em;font-weight:bold'>")
            if active:
                streak_count += 1
                cell_html += "●"
            else:
                cell_html += "○"
            cell_html += "</div>"
            cols[i+1].markdown(cell_html, unsafe_allow_html=True)

    st.caption(f"🔥 {streak_count}-day streak across the last 4 weeks. Green ● = active day.")

    st.divider()

    # ── Upcoming Reviews Bar Chart ─────────────────────────────────────────
    st.subheader("📬 Upcoming Reviews — Next 14 Days")

    if upcoming:
        try:
            import plotly.express as px
            import plotly.graph_objects as go

            dates = [d["date"][-5:] for d in upcoming]  # MM-DD
            due_counts = [d.get("due_count", 0) for d in upcoming]
            today_str = str(__import__('datetime').date.today())[-5:]
            colors = ["#ff6b6b" if dates[i] == today_str else "#51cf66" for i in range(len(dates))]

            fig = go.Figure()
            fig.add_bar(x=dates, y=due_counts, marker_color=colors, text=due_counts, textposition="outside")
            fig.update_layout(
                margin={"l": 0, "r": 0, "t": 10, "b": 0},
                height=220,
                plot_bgcolor="transparent",
                paper_bgcolor="transparent",
                font={"color": "#cccccc", "size": 11},
                xaxis={"tickangle": -45, "showgrid": False, "title": ""},
                yaxis={"showgrid": False, "title": ""},
            )
            st.plotly_chart(fig, use_container_width=True)
            st.caption("🔴 Today | 🟢 Upcoming days")
        except Exception:
            # Fallback: ASCII-style list
            for d in upcoming:
                today_marker = " 🔴" if d["date"] == str(__import__('datetime').date.today()) else ""
                st.write(f"{d['date'][-5:]}: {d.get('due_count',0)} cards due{today_marker}")
    else:
        st.info("No upcoming reviews scheduled.")

    st.divider()

    # ── Today's Focus ─────────────────────────────────────────────────────
    st.subheader(f"🎯 Today's Focus — {total_due} cards due")

    if not topic_breakdown:
        st.success("🎉 No cards due today! Enjoy a well-deserved break.")
    else:
        for topic in topic_breakdown:
            tid = topic.get("topic_id")
            tname = topic.get("topic_name", "Unknown")
            count = topic.get("due_count", 0)
            cols_row = st.columns([4, 1])
            with cols_row[0]:
                st.write(f"**{tname}** — `{count} cards due`")
            with cols_row[1]:
                if st.button(f"Start Review →", key=f"review_today_{tid}"):
                    st.session_state["page"] = "Study Session"
                    st.rerun()
        st.caption("All due cards are sourced from your SM-2 review queue.")


def main():
    # Auth guard — all pages except Login require a token
    public_pages = {"Login"}
    if st.session_state.get("page", "Login") not in public_pages and not st.session_state.get("jwt_token"):
        st.session_state["page"] = "Login"

    sidebar_nav()
    page = st.session_state.get("page", "Login")

    if page == "Login":
        page_login()
    elif page == "Dashboard":
        require_auth()
        page_dashboard()
    elif page == "Study Session":
        require_auth()
        page_study_session()
    elif page == "Focus Mode":
        require_auth()
        page_focus_mode()
    elif page == "Exam Mode":
        require_auth()
        page_exam_mode()
    elif page == "Topic Trends":
        require_auth()
        page_topic_trends()
    elif page == "Profile":
        require_auth()
        page_profile()
    elif page == "Achievements":
        require_auth()
        page_achievements()
    elif page == "History":
        require_auth()
        page_history()
    elif page == "Study Plan":
        require_auth()
        page_study_plan()


if __name__ == "__main__":
    main()
